[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustcraft_codegen = { path = "./rustcraft_codegen" }
jni = "0.21.1"

[lib]
crate-type = ["lib"]
